FROM ruby:3.3-alpine

RUN apk add --no-cache build-base

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY config.ru ./
COPY bin ./bin
COPY lib ./lib
COPY test ./test

CMD ["ruby", "-Itest", "test/all_test.rb"]
