services:
  api:
    build: .
    command: mix run --no-halt
    environment:
      REDIS_URL: redis://redis:6379/0
      TASK_DURATION_SCALE: 1.0
      WORKER_ENABLED: "false"
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    command: mix run --no-halt
    environment:
      REDIS_URL: redis://redis:6379/0
      TASK_DURATION_SCALE: 1.0
      WORKER_ENABLED: "true"
      PORT: 8001
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: mix test
    environment:
      REDIS_URL: redis://redis:6379/1
      TASK_DURATION_SCALE: 0.0
      WORKER_ENABLED: "false"
      PORT: 8002
    depends_on:
      - redis
    profiles:
      - test
