FROM elixir:1.16-alpine

RUN apk add --no-cache build-base git

WORKDIR /app

ENV MIX_ENV=test

COPY mix.exs mix.lock ./
RUN mix local.hex --force && mix local.rebar --force && mix deps.get

COPY config ./config
COPY lib ./lib
COPY test ./test

CMD ["mix", "test"]
